/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import DAO.StockDao;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.StockModel;



/**
 *
 * @author GANZA
 */
public class admGUI extends javax.swing.JFrame {
    private StockDao dao;
    String filename =null;
    byte[] personImage=null;
    private Icon imageIcon;
    private java.util.Date currentDate;

    /**
     * Creates new form admGUI
     */
    public admGUI() {
        initComponents();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pNameTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pIdTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        quantityTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cpTxt = new javax.swing.JTextField();
        spTxt = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        selectAllBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        searchProTxt = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        dDateTxt = new com.toedter.calendar.JDateChooser();
        eDateTxt = new com.toedter.calendar.JDateChooser();
        resetBtn = new javax.swing.JButton();
        searchProductBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        firstNameTxt = new javax.swing.JTextField();
        lastNameTxt = new javax.swing.JTextField();
        dutyTxt = new javax.swing.JTextField();
        salaryTxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        regBtn = new javax.swing.JButton();
        selAllBtn = new javax.swing.JButton();
        logOuTEBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        SearchETxt = new javax.swing.JTextField();
        updTxt = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        resetEBtn = new javax.swing.JButton();
        bImageTxt = new javax.swing.JLabel();
        searchEBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        adIDTxt = new javax.swing.JTextField();
        namesTxt = new javax.swing.JTextField();
        usernameTxt = new javax.swing.JTextField();
        admPassTxt = new javax.swing.JPasswordField();
        jLabel25 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        searchAdmTxt = new javax.swing.JTextField();
        searchAdmBtn = new javax.swing.JButton();
        logoutAdm = new javax.swing.JButton();
        regAdmBtn = new javax.swing.JButton();
        updAdmTxt = new javax.swing.JButton();
        delAdmTxt = new javax.swing.JButton();
        seleAlBtn = new javax.swing.JButton();
        resetABtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        eAnnouncTxt = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        uplogoutBtn = new javax.swing.JButton();
        dateUpdateTxt = new com.toedter.calendar.JDateChooser();
        resetUpd = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setForeground(new java.awt.Color(153, 255, 0));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Trajan Pro 3", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("PRODUCTS INFORMATION");

        jLabel3.setBackground(new java.awt.Color(255, 255, 102));
        jLabel3.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel3.setText("Product Name");

        pNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNameTxtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel4.setText("Product ID");

        jLabel5.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel5.setText("Quantity");

        jLabel6.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel6.setText("Delivery Date");

        jLabel7.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel7.setText("Expiry Date");

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel1.setText("Purchase Price/CP");

        jLabel8.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel8.setText("Selling Price/SP");

        registerBtn.setBackground(new java.awt.Color(0, 0, 0));
        registerBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 255, 0));
        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        selectAllBtn.setBackground(new java.awt.Color(0, 0, 0));
        selectAllBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        selectAllBtn.setForeground(new java.awt.Color(255, 255, 0));
        selectAllBtn.setText("Select All");
        selectAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllBtnActionPerformed(evt);
            }
        });

        logOutBtn.setBackground(new java.awt.Color(0, 0, 0));
        logOutBtn.setForeground(new java.awt.Color(255, 255, 0));
        logOutBtn.setText("LOGOUT");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        jLabel18.setText("Search Product ID");

        deleteBtn.setBackground(new java.awt.Color(0, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 0));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(0, 0, 0));
        updateBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 0));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(searchProTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(updateBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn)
                .addGap(25, 25, 25))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchProTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBtn)
                            .addComponent(updateBtn))
                        .addGap(2, 2, 2))
                    .addComponent(jLabel18))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        resetBtn.setBackground(new java.awt.Color(0, 0, 0));
        resetBtn.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(255, 255, 0));
        resetBtn.setText("RESET");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        searchProductBtn.setBackground(new java.awt.Color(0, 0, 0));
        searchProductBtn.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        searchProductBtn.setForeground(new java.awt.Color(255, 255, 0));
        searchProductBtn.setText("Search");
        searchProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProductBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(registerBtn)
                            .addGap(62, 62, 62)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(searchProductBtn)
                                    .addGap(52, 52, 52)
                                    .addComponent(selectAllBtn)
                                    .addGap(57, 57, 57)
                                    .addComponent(resetBtn)))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(153, 153, 153)
                                .addComponent(pNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(logOutBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(pNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel7)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(spTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(dDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(eDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(119, 119, 119))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(registerBtn)
                                .addComponent(searchProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(selectAllBtn)
                            .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logOutBtn))))
        );

        jTabbedPane1.addTab("Products", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("EMPLOYEES INFORMATION");

        jLabel13.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel13.setText("First Name");

        jLabel14.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel14.setText("Last Name");

        jLabel15.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel15.setText("Duty");

        jLabel16.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel16.setText("Salary");

        jLabel17.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel17.setText("Password");

        regBtn.setBackground(new java.awt.Color(0, 0, 0));
        regBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        regBtn.setForeground(new java.awt.Color(255, 255, 0));
        regBtn.setText("Register");
        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });

        selAllBtn.setBackground(new java.awt.Color(0, 0, 0));
        selAllBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        selAllBtn.setForeground(new java.awt.Color(255, 255, 0));
        selAllBtn.setText("Select All");
        selAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selAllBtnActionPerformed(evt);
            }
        });

        logOuTEBtn.setBackground(new java.awt.Color(0, 0, 0));
        logOuTEBtn.setForeground(new java.awt.Color(255, 255, 0));
        logOuTEBtn.setText("LOGOUT");
        logOuTEBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOuTEBtnActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel26.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        jLabel26.setText("Search Employee ID");

        SearchETxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchETxtActionPerformed(evt);
            }
        });

        updTxt.setBackground(new java.awt.Color(0, 0, 0));
        updTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        updTxt.setForeground(new java.awt.Color(255, 255, 0));
        updTxt.setText("Update");
        updTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updTxtActionPerformed(evt);
            }
        });

        delBtn.setBackground(new java.awt.Color(0, 0, 0));
        delBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        delBtn.setForeground(new java.awt.Color(255, 255, 0));
        delBtn.setText("Delete");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SearchETxt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(updTxt)
                .addGap(18, 18, 18)
                .addComponent(delBtn)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(SearchETxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updTxt)
                            .addComponent(delBtn))))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        resetEBtn.setBackground(new java.awt.Color(0, 0, 0));
        resetEBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        resetEBtn.setForeground(new java.awt.Color(255, 255, 0));
        resetEBtn.setText("Reset");
        resetEBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetEBtnActionPerformed(evt);
            }
        });

        searchEBtn.setBackground(new java.awt.Color(0, 0, 0));
        searchEBtn.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        searchEBtn.setForeground(new java.awt.Color(255, 255, 0));
        searchEBtn.setText("Search");
        searchEBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(logOuTEBtn)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(regBtn)
                                .addGap(66, 66, 66)
                                .addComponent(searchEBtn)
                                .addGap(53, 53, 53)
                                .addComponent(selAllBtn)
                                .addGap(62, 62, 62)
                                .addComponent(resetEBtn))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(171, 171, 171)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firstNameTxt)
                                    .addComponent(lastNameTxt)
                                    .addComponent(dutyTxt)
                                    .addComponent(salaryTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(passwordTxt))
                                .addGap(37, 37, 37)
                                .addComponent(bImageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bImageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(dutyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selAllBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(searchEBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(resetEBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(regBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logOuTEBtn))
        );

        jTabbedPane1.addTab("Employess", jPanel3);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel19.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 51));
        jLabel19.setText("ADMINISTRATOR  INFORMATION");

        jLabel20.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel20.setText("ADID");

        jLabel21.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel21.setText("Names");

        jLabel23.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel23.setText("Username");

        jLabel24.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel24.setText("Password");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel29.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Search By ID");

        searchAdmBtn.setBackground(new java.awt.Color(0, 0, 0));
        searchAdmBtn.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        searchAdmBtn.setForeground(new java.awt.Color(255, 255, 0));
        searchAdmBtn.setText("Search");
        searchAdmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAdmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel29)
                .addGap(30, 30, 30)
                .addComponent(searchAdmTxt)
                .addGap(18, 18, 18)
                .addComponent(searchAdmBtn)
                .addGap(109, 109, 109))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(searchAdmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchAdmBtn))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        logoutAdm.setBackground(new java.awt.Color(0, 0, 0));
        logoutAdm.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        logoutAdm.setForeground(new java.awt.Color(255, 255, 0));
        logoutAdm.setText("LOGOUT");
        logoutAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutAdmActionPerformed(evt);
            }
        });

        regAdmBtn.setBackground(new java.awt.Color(0, 0, 0));
        regAdmBtn.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        regAdmBtn.setForeground(new java.awt.Color(255, 255, 51));
        regAdmBtn.setText("Register");
        regAdmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regAdmBtnActionPerformed(evt);
            }
        });

        updAdmTxt.setBackground(new java.awt.Color(0, 0, 0));
        updAdmTxt.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        updAdmTxt.setForeground(new java.awt.Color(255, 255, 0));
        updAdmTxt.setText("Update");
        updAdmTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updAdmTxtActionPerformed(evt);
            }
        });

        delAdmTxt.setBackground(new java.awt.Color(0, 0, 0));
        delAdmTxt.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        delAdmTxt.setForeground(new java.awt.Color(255, 255, 0));
        delAdmTxt.setText("Delete");
        delAdmTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delAdmTxtActionPerformed(evt);
            }
        });

        seleAlBtn.setBackground(new java.awt.Color(0, 0, 0));
        seleAlBtn.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        seleAlBtn.setForeground(new java.awt.Color(255, 255, 0));
        seleAlBtn.setText("Select all");
        seleAlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleAlBtnActionPerformed(evt);
            }
        });

        resetABtn.setBackground(new java.awt.Color(51, 51, 51));
        resetABtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        resetABtn.setForeground(new java.awt.Color(255, 255, 0));
        resetABtn.setText("Reset");
        resetABtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetABtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel23)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addGap(48, 48, 48)))
                            .addComponent(jLabel24))
                        .addGap(133, 133, 133)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(admPassTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(namesTxt)
                            .addComponent(usernameTxt)
                            .addComponent(adIDTxt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(logoutAdm))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(regAdmBtn)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel19))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(updAdmTxt)
                                .addGap(26, 26, 26)
                                .addComponent(delAdmTxt)
                                .addGap(38, 38, 38)
                                .addComponent(seleAlBtn)
                                .addGap(28, 28, 28)
                                .addComponent(resetABtn))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 159, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel20))
                            .addComponent(adIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21))
                    .addComponent(namesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(admPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(regAdmBtn)
                        .addComponent(delAdmTxt)
                        .addComponent(seleAlBtn)
                        .addComponent(updAdmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(resetABtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel25)
                .addGap(37, 37, 37)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(logoutAdm)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Admin", jPanel1);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel10)
                .addGap(177, 580, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel10)
                .addContainerGap(595, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", jPanel7);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 0));
        jLabel27.setText("Updates to Employees");

        jLabel28.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel28.setText("Date");

        jLabel30.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel30.setText("Announcement");

        eAnnouncTxt.setColumns(20);
        eAnnouncTxt.setRows(5);
        jScrollPane1.setViewportView(eAnnouncTxt);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 0));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel32.setText("Click");

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 0));
        jButton3.setText("here");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel33.setText("to see Employees opinions/ requests");

        uplogoutBtn.setBackground(new java.awt.Color(0, 0, 0));
        uplogoutBtn.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        uplogoutBtn.setForeground(new java.awt.Color(255, 255, 0));
        uplogoutBtn.setText("LOGOUT");
        uplogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uplogoutBtnActionPerformed(evt);
            }
        });

        resetUpd.setBackground(new java.awt.Color(0, 0, 0));
        resetUpd.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        resetUpd.setForeground(new java.awt.Color(255, 255, 0));
        resetUpd.setText("RESET");
        resetUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetUpdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel28))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateUpdateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel27))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel32)
                        .addGap(6, 6, 6)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33)))
                .addContainerGap(307, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(uplogoutBtn)
                .addGap(282, 282, 282))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetUpd)
                .addGap(54, 54, 54))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel28)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateUpdateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(resetUpd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jButton3)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uplogoutBtn)
                .addGap(9, 9, 9))
        );

        jTabbedPane1.addTab("Updates", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutAdmActionPerformed
        // third tab
        dashboard jf1=new dashboard();
        jf1.show();
        dispose();
    }//GEN-LAST:event_logoutAdmActionPerformed

    private void searchEBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEBtnActionPerformed

          searchSelEmp jf1=new searchSelEmp();
        jf1.show();
        dispose();



//          if (SearchETxt.getText().trim().isEmpty()) {
//        JOptionPane.showMessageDialog(this, "Employee ID to search is mandatory");
//    } else {
//        try {
//            int employeeId = Integer.parseInt(SearchETxt.getText());
//            
//            StockModel sObj = new StockModel();
//            sObj.setEid(employeeId);  // Set the Employee ID for searching
//
//            StockDao dao = new StockDao();
//            StockModel sm = dao.searchEmployee(sObj);
//
//            if (sm != null) {
//                firstNameTxt.setText(sm.getEfname());
//                lastNameTxt.setText(sm.getElname());
//                dutyTxt.setText(sm.getDuty());
//                 // salaryTxt.setText(sm.getSalary().toString());
//                // Salary should be added here
//                 //salaryTxt.setText(sm.salaryTxt());
//                passwordTxt.setText(sm.getPassword());
//                // Set the retrieved salary wherever needed
//            } else {
//                JOptionPane.showMessageDialog(this, "Employee not Found");
//                        clearEmployeeFields();
//
//            }
//        } catch (NumberFormatException ex) {
//            JOptionPane.showMessageDialog(this, "Invalid Employee ID format");
//        }
//    }
          
    }//GEN-LAST:event_searchEBtnActionPerformed

    private void SearchETxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchETxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchETxtActionPerformed

    private void logOuTEBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOuTEBtnActionPerformed
        // on tab 2
        dashboard jf1=new dashboard();
        jf1.show();
        dispose();
    }//GEN-LAST:event_logOuTEBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // On the first tab
        dashboard jf1=new dashboard();
        jf1.show();
        dispose();
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // Update Product
          SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
              String dDate=sdf.format(dDateTxt.getDate());
              String eDate=sdf.format(eDateTxt.getDate());
          if(pNameTxt.getText().trim().isEmpty() ||nameCheck((pNameTxt.getText()))==false){
            JOptionPane.showMessageDialog(this, "Product id is Mandatory and should be a string","Field Mandatory",JOptionPane.WARNING_MESSAGE);
        }else if(pIdTxt.getText().trim().isEmpty()|| !isInteger((pIdTxt.getText()))){
            JOptionPane.showMessageDialog(this, "Product ID is Mandatory","Field Mandatory",JOptionPane.WARNING_MESSAGE);
        } else if(quantityTxt.getText().trim().isEmpty()|| !isInteger((pIdTxt.getText()))){
            JOptionPane.showMessageDialog(this, "product quantity is Mandatory","Field Mandatory",JOptionPane.WARNING_MESSAGE);
        }
        //Dates are not validated
        
        else if (dDateTxt.getDate() == null) {
    JOptionPane.showMessageDialog(this, "Product Delivery date is Mandatory", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
} else if (eDateTxt.getDate() == null) {
    JOptionPane.showMessageDialog(this, "Product Expiry date is Mandatory", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
}
          else if(cpTxt.getText().trim().isEmpty()|| !isInteger((pIdTxt.getText()))){
              JOptionPane.showMessageDialog(this, "product cp is Mandatory","Field Mandatory",JOptionPane.WARNING_MESSAGE);
          }else if(spTxt.getText().trim().isEmpty()|| !isInteger((pIdTxt.getText()))){
              JOptionPane.showMessageDialog(this, "product sp is Mandatory","Field Mandatory",JOptionPane.WARNING_MESSAGE);
          }
          //add quantity should have value that is >=0
          else{
              // 2. check book id if has 3 characters
              if(pIdTxt.getText().length() ==3){
                  // call the Model
                  StockModel sObj = new StockModel();
                  sObj.setPname(pNameTxt.getText());
                  //     //sObj.setPid(pIdTxt.getText());
                  sObj.setPid(Integer.valueOf(pIdTxt.getText()));
                  sObj.setQuantity(Integer.valueOf(quantityTxt.getText()));
                  sObj.setCp(Integer.valueOf(cpTxt.getText()));
                  sObj.setSp(Integer.valueOf(spTxt.getText()));
                  
                  //pIdTxt.setText(sObj.setPid().toString());
                  // quantityTxt.setText(sObj.setQuantity().toString());
                  //Dates

                  
              sObj.setDdate(dDate);
              sObj.setEdate(eDate);
                  
                      //sObj.setDdate(Date.valueOf(eDateTxt.getDate()));
                  
                  // call dao
                  StockDao st = new StockDao();
                  String feedBackl;
                  feedBackl = st.updateProduct(sObj);
                  JOptionPane.showMessageDialog(this, feedBackl);
                  clearProducFields();
              }else{
                  JOptionPane.showMessageDialog(this, "product Id should have min \n and max 3 characters","product ID Length",JOptionPane.WARNING_MESSAGE);
                  
              }
              
          }
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void pNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNameTxtActionPerformed

    private void uplogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uplogoutBtnActionPerformed
        // last tab
         dashboard jf1=new dashboard();
        jf1.show();
        dispose();
    }//GEN-LAST:event_uplogoutBtnActionPerformed
     public static boolean isDateAfter(Date date) {
        // Create a Calendar instance
        Calendar RDate = Calendar.getInstance();
        RDate.set(2023, Calendar.NOVEMBER, 24);

        // Create a Calendar instance for the provided date
        Calendar providedDate = Calendar.getInstance();
        providedDate.setTime(date);

        // Compare the provided date with November 24, 2023
        return providedDate.after(RDate);
    }
    
    private boolean nameCheck(String input){
          return  Pattern.matches("[a-zA-Z]+",input);
      }
     private boolean isDateInFuture(Date date) {
   // Date currentDate = new Date();
    
    // Create a Calendar instance for the current date
    Calendar currentCalendar = Calendar.getInstance();
    currentCalendar.setTime(currentDate);

    // Create a Calendar instance for the input date
    Calendar inputCalendar = Calendar.getInstance();
    inputCalendar.setTime(date);

    // Compare the input date with the current date
    return inputCalendar.after(currentCalendar);
}
     private boolean isInteger(String input) {
    try {
        Integer.parseInt(input);
        return true;
    } catch (NumberFormatException e) {
        return false;
    }
}
      public static boolean isQuantityValid(int quantity) {
        return quantity > 0;
    }
    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
          SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String dDate = sdf.format(dDateTxt.getDate());
    String eDate = sdf.format(eDateTxt.getDate());

   // boolean exists = checkValueInDatabase(pNameTxt.getText().toLowerCase());

     if (pNameTxt.getText().trim().isEmpty() || nameCheck((pNameTxt.getText()))==false) {
        JOptionPane.showMessageDialog(this, "Product name is Mandatory and Name should be a string", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
    } else if (pIdTxt.getText().trim().isEmpty()  || !isInteger((pIdTxt.getText()))) {
        JOptionPane.showMessageDialog(this, "Product ID is Mandatory and ID should be an integer", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
    } else if (quantityTxt.getText().trim().isEmpty() || !isInteger(quantityTxt.getText()) || !isQuantityValid(Integer.parseInt(quantityTxt.getText()))) {
    JOptionPane.showMessageDialog(this, "Product quantity is Mandatory and should be not less or equal to 0", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
}

//    else if (dDateTxt.getDate() == null ) {
//        JOptionPane.showMessageDialog(this, "Product Delivery date is Mandatory", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
//    } else if (eDateTxt.getDate() == null ) {
//        JOptionPane.showMessageDialog(this, "Product Expiry date is Mandatory and should be in Date Format", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
//    }
    else if (cpTxt.getText().trim().isEmpty()||!isInteger((cpTxt.getText()))) {
        JOptionPane.showMessageDialog(this, "Product CP is Mandatory and shoul dbe an integer", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
    } else if (spTxt.getText().trim().isEmpty()||!isInteger((spTxt.getText()))) {
        JOptionPane.showMessageDialog(this, "Product SP is Mandatory and should be an integer", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
    } else {
        // Additional validation and processing logic
        if (pIdTxt.getText().length() == 3) {
            // Call the Model
            StockModel sObj = new StockModel();
            sObj.setPname(pNameTxt.getText().toLowerCase());
            sObj.setPid(Integer.valueOf(pIdTxt.getText()));
            sObj.setQuantity(Integer.valueOf(quantityTxt.getText()));
            sObj.setCp(Integer.valueOf(cpTxt.getText()));
            sObj.setSp(Integer.valueOf(spTxt.getText()));
            sObj.setDdate(dDate);
            sObj.setEdate(eDate);

            // Call DAO
            StockDao st = new StockDao();
            String feedback = st.recordProduct(sObj);
            JOptionPane.showMessageDialog(this, feedback);
            clearProducFields();
        } else {
            JOptionPane.showMessageDialog(this, "Product ID should have min and max 3 characters", "Product ID Length", JOptionPane.WARNING_MESSAGE);
        }
    }
    }//GEN-LAST:event_registerBtnActionPerformed

    
    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed
        // TODO add your handling code here:
        // to record employees
           if(firstNameTxt.getText().trim().isEmpty()|| nameCheck((firstNameTxt.getText()))==false){
           JOptionPane.showMessageDialog(this, " first name is mandatory and should be a String","Field required",JOptionPane.WARNING_MESSAGE);
       } else if(lastNameTxt.getText().trim().isEmpty()|| nameCheck((lastNameTxt.getText()))==false){
            JOptionPane.showMessageDialog(this, "first name name is mandatory and should be a String","Field required",JOptionPane.WARNING_MESSAGE);
       } else if(dutyTxt.getText().trim().isEmpty()|| nameCheck((dutyTxt.getText()))==false){
            JOptionPane.showMessageDialog(this, "duty is mandatory","Field required",JOptionPane.WARNING_MESSAGE);
            //salary should be added
       }else if(passwordTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "password is mandatory","Field required",JOptionPane.WARNING_MESSAGE);
       } else if(salaryTxt.getText().trim().isEmpty()||!isInteger((quantityTxt.getText()))|| !isQuantityValid(Integer.parseInt(quantityTxt.getText()))){
           JOptionPane.showMessageDialog(this, "Salary is mandatory and should be an integer","Field required",JOptionPane.WARNING_MESSAGE);
       }
       else{
          // JOptionPane.showMessageDialog(this, "Data SAVED");
            // call the Model
                StockModel sOb = new StockModel();
                sOb.setEfname(firstNameTxt.getText());
                sOb.setElname(lastNameTxt.getText());
                sOb.setDuty(dutyTxt.getText());
                 sOb.setSalary(Double.valueOf(salaryTxt.getText()));
                sOb.setPassword(passwordTxt.getText());
                // call dao
                StockDao d = new StockDao();
                String feedBack = d.recordEmployee(sOb);
                JOptionPane.showMessageDialog(this, feedBack);
//                //update book
//                String updanswer=dao.updateBook(bookObj);
//                JOptionPane.showMessageDialog(this, updanswer);
                clearEmployeeFields();
       }
      
    }//GEN-LAST:event_regBtnActionPerformed

    private void updTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updTxtActionPerformed
        // Update Employees
         if(firstNameTxt.getText().trim().isEmpty()|| nameCheck((firstNameTxt.getText()))==false){
           JOptionPane.showMessageDialog(this, " first name is mandatory and should be a string","Field required",JOptionPane.WARNING_MESSAGE);
       } else if(lastNameTxt.getText().trim().isEmpty()|| nameCheck((lastNameTxt.getText()))==false){
            JOptionPane.showMessageDialog(this, "first name name is mandatory and should be a string","Field required",JOptionPane.WARNING_MESSAGE);
       } else if(dutyTxt.getText().trim().isEmpty()|| nameCheck((dutyTxt.getText()))==false){
            JOptionPane.showMessageDialog(this, "duty is mandatory and should be a string","Field required",JOptionPane.WARNING_MESSAGE);
            //salary should be added
       }else if(passwordTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "password is mandatory","Field required",JOptionPane.WARNING_MESSAGE);
       } else if(salaryTxt.getText().trim().isEmpty()||!isInteger((salaryTxt.getText()))){
           JOptionPane.showMessageDialog(this, "Salary is mandatory and should be an integer","Field required",JOptionPane.WARNING_MESSAGE);
       } else if(SearchETxt.getText().trim().isEmpty()||!isInteger((SearchETxt.getText()))){
           JOptionPane.showMessageDialog(this, "Employee Id is mandatory and should be an integer","Field required",JOptionPane.WARNING_MESSAGE);
       }else{
           
          StockModel sOb = new StockModel();
        sOb.setEfname(firstNameTxt.getText());
        sOb.setElname(lastNameTxt.getText());
        sOb.setPassword(passwordTxt.getText());
        sOb.setSalary(Integer.valueOf(salaryTxt.getText()));
        sOb.setEid(Integer.valueOf(SearchETxt.getText()));
          sOb.setDuty(dutyTxt.getText());
        StockDao sd = new StockDao();
        String feedBack = sd.updateEmployee(sOb);
        JOptionPane.showMessageDialog(this, feedBack);

        // Clear fields after update
        clearEmployeeFields();
       }
        
    }//GEN-LAST:event_updTxtActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // delete Employee
          if(SearchETxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Employee ID to delete is mandatory");
        }else{
            StockModel sOb = new StockModel();
               sOb.setEid(Integer.valueOf(SearchETxt.getText()));
            StockDao ed = new StockDao();
            String feedback = ed.deleteEmployee(sOb);
            JOptionPane.showMessageDialog(this, feedback);
        }
           clearEmployeeFields();
        
    }//GEN-LAST:event_delBtnActionPerformed

    private void regAdmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regAdmBtnActionPerformed
        // Register admin
         if(adIDTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Admin id is Mandatory","Field Mandatory",JOptionPane.WARNING_MESSAGE);
        }else if(namesTxt.getText().trim().isEmpty()|| nameCheck((namesTxt.getText()))==false){
            JOptionPane.showMessageDialog(this, "Name is Mandatory","Field Mandatory",JOptionPane.WARNING_MESSAGE);
        }else if(usernameTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Username is Mandatory","Field Mandatory",JOptionPane.WARNING_MESSAGE);
        }else if(admPassTxt.getText().trim().isEmpty()){
             JOptionPane.showMessageDialog(this, "Password is Mandatory","Field Mandatory",JOptionPane.WARNING_MESSAGE);
        }
        //add if admin Id does not exist in table the do the following
        else {
      
            
                // call the Model
                StockModel sm= new StockModel();
                sm.setADID(adIDTxt.getText());
                sm.setNames(namesTxt.getText());
                sm.setAdusername(usernameTxt.getText());
                sm.setAdpassword(admPassTxt.getText());
                // call dao
                StockDao sd = new StockDao();
                String feedBack = sd.recordAdmin(sm);
                JOptionPane.showMessageDialog(this, feedBack);
        

           clearAdminFields();
            
        }
           
    }//GEN-LAST:event_regAdmBtnActionPerformed

    private void updAdmTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updAdmTxtActionPerformed
        // update admin
        
         if(adIDTxt.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this, "Admin id is mandatory","Field required",JOptionPane.WARNING_MESSAGE);  
       } else if(namesTxt.getText().trim().isEmpty()|| nameCheck((namesTxt.getText()))==false){
            JOptionPane.showMessageDialog(this, "Names are mandatory","Field required",JOptionPane.WARNING_MESSAGE);
       }else if(usernameTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Username is mandatory","Field required",JOptionPane.WARNING_MESSAGE);
       }else if(admPassTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "password is mandatory","Field required",JOptionPane.WARNING_MESSAGE);
       }
       else{
            // JOptionPane.showMessageDialog(this, "Data SAVED");
            // call the Model
                StockModel sm = new StockModel();
                sm.setADID(adIDTxt.getText());
                sm.setNames(namesTxt.getText());
                sm.setAdusername(usernameTxt.getText());
                 sm.setAdpassword(admPassTxt.getText());
                   
                // call dao
                StockDao sd = new StockDao();
              
                //update book
                String updanswer=sd.updateAdmin(sm);
                JOptionPane.showMessageDialog(this, updanswer); 
                clearAdminFields();
       }
      
        
       
//       else{
//          JOptionPane.showMessageDialog(this, "Book Id should have min \n and max 3 characters","Book ID Length",JOptionPane.WARNING_MESSAGE); 
//       }
        
        
    }//GEN-LAST:event_updAdmTxtActionPerformed

    private void delAdmTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delAdmTxtActionPerformed
        // Delete Admin
           if(adIDTxt.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this, "Admin ID is mandatory","Field required",JOptionPane.WARNING_MESSAGE);
           
       } 
           else{
          // JOptionPane.showMessageDialog(this, "Data SAVED");
            // call the Model
                StockModel sm = new StockModel();
                sm.setADID(adIDTxt.getText());
                sm.setNames(namesTxt.getText());
                  sm.setNames(usernameTxt.getText());
                   sm.setNames(admPassTxt.getText());
                // call dao
                StockDao sd = new StockDao();
              ;
                
                String deldanswer=sd.deleteAdmin(sm);
                JOptionPane.showMessageDialog(this, deldanswer);
                clearAdminFields();
       }
       
    }//GEN-LAST:event_delAdmTxtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //  Updates or information to Employees
           if(dateUpdateTxt.getDate()==null){
           JOptionPane.showMessageDialog(this, "Date is mandatory","Field required",JOptionPane.WARNING_MESSAGE);
       }else 
              if(eAnnouncTxt.getText().trim().isEmpty()){
             JOptionPane.showMessageDialog(this, "Admin ID is mandatory","Field required",JOptionPane.WARNING_MESSAGE);
       }else{
            StockModel sm = new StockModel();
             SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
              String updDate=sdf.format(dateUpdateTxt.getDate());
            
               sm.setUpdDate(updDate);
                sm.setWorkUpdates(eAnnouncTxt.getText());
                    StockDao sd = new StockDao();
              
                
                String infanswer=sd.workUpdatesInfo(sm);
                JOptionPane.showMessageDialog(this, infanswer);
                 clearUpdateFields();
       }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchAdmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAdmBtnActionPerformed
        // to search Admin
              if (searchAdmTxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Admin ID to search is mandatory");
    } else {
        try {
           // int adminId = Integer.parseInt(searchAdmTxt.getText());
            String adminId=  searchAdmTxt.getText();
            
            StockModel sObj = new StockModel();
            sObj.setADID(adminId);  

            StockDao dao = new StockDao();
            StockModel sm = dao.searchAdmin(sObj);

            if (sm != null) {
                adIDTxt.setText(sm.getADID());
                namesTxt.setText(sm.getNames());
                usernameTxt.setText(sm.getAdusername());
                  admPassTxt.setText(sm.getAdpassword());
              
                // Set the retrieved salary wherever needed
            } else {
                JOptionPane.showMessageDialog(this, "Admin ID not Found");
                      

            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid admin ID format");
        }
          clearEmployeeFields();
    }
    }//GEN-LAST:event_searchAdmBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // Delete product
          if(searchProTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Product ID to delete is mandatory");
        }else{
            StockModel sOb = new StockModel();
               sOb.setPid(Integer.valueOf(searchProTxt.getText()));
            StockDao ed = new StockDao();
            String feedback = ed.deleteProduct(sOb);
            JOptionPane.showMessageDialog(this, feedback);
        }
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Button clicked to see employees opinions
         opinions jf2=new opinions();
                    jf2.show();
                    dispose();  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // reset all product fields;
        clearProducFields();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void resetEBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetEBtnActionPerformed
        // Reset Employee Data
        clearEmployeeFields();
    }//GEN-LAST:event_resetEBtnActionPerformed

    private void resetABtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetABtnActionPerformed
        // Reset Admin Information
        clearAdminFields();
    }//GEN-LAST:event_resetABtnActionPerformed

    private void resetUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetUpdActionPerformed
        // TODO add your handling code here:
        clearUpdateFields();
    }//GEN-LAST:event_resetUpdActionPerformed

    private void searchProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProductBtnActionPerformed
        // Search product
          searchSelProd jf1=new searchSelProd();
        jf1.show();
        dispose();
    }//GEN-LAST:event_searchProductBtnActionPerformed

    private void selectAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllBtnActionPerformed
        // Select all products
          searchSelProd jf1=new searchSelProd();
        jf1.show();
        dispose();
    }//GEN-LAST:event_selectAllBtnActionPerformed

    private void selAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selAllBtnActionPerformed
        // TODO add your handling code here:
        searchSelEmp jf1=new searchSelEmp();
        jf1.show();
        dispose();
    }//GEN-LAST:event_selAllBtnActionPerformed

    private void seleAlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleAlBtnActionPerformed
        // TODO add your handling code here:
        searchSelAdmin jf1=new searchSelAdmin();
        jf1.show();
        dispose();
    }//GEN-LAST:event_seleAlBtnActionPerformed
private void clearUpdateFields(){
    eAnnouncTxt.setText("");
    dateUpdateTxt.setDate(null);
}
    
    private void clearEmployeeFields() {
    firstNameTxt.setText("");
    lastNameTxt.setText("");
    dutyTxt.setText("");
    passwordTxt.setText("");
    salaryTxt.setText("");
    SearchETxt.setText("");
}
    private void clearAdminFields() {
    adIDTxt.setText("");
    namesTxt.setText("");
    usernameTxt.setText("");
    admPassTxt.setText("");
    searchAdmTxt.setText("");
}
      private void clearProducFields() {

    pNameTxt.setText("");
    pIdTxt.setText("");
    quantityTxt.setText("");
    dDateTxt.setDate(null);
   eDateTxt.setDate(null);
    cpTxt.setText("");
    spTxt.setText("");
    searchProTxt.setText("");
}  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SearchETxt;
    private javax.swing.JTextField adIDTxt;
    private javax.swing.JPasswordField admPassTxt;
    private javax.swing.JLabel bImageTxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField cpTxt;
    private com.toedter.calendar.JDateChooser dDateTxt;
    private com.toedter.calendar.JDateChooser dateUpdateTxt;
    private javax.swing.JButton delAdmTxt;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField dutyTxt;
    private javax.swing.JTextArea eAnnouncTxt;
    private com.toedter.calendar.JDateChooser eDateTxt;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JButton logOuTEBtn;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton logoutAdm;
    private javax.swing.JTextField namesTxt;
    private javax.swing.JTextField pIdTxt;
    private javax.swing.JTextField pNameTxt;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JButton regAdmBtn;
    private javax.swing.JButton regBtn;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton resetABtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton resetEBtn;
    private javax.swing.JButton resetUpd;
    private javax.swing.JTextField salaryTxt;
    private javax.swing.JButton searchAdmBtn;
    private javax.swing.JTextField searchAdmTxt;
    private javax.swing.JButton searchEBtn;
    private javax.swing.JTextField searchProTxt;
    private javax.swing.JButton searchProductBtn;
    private javax.swing.JButton selAllBtn;
    private javax.swing.JButton seleAlBtn;
    private javax.swing.JButton selectAllBtn;
    private javax.swing.JTextField spTxt;
    private javax.swing.JButton updAdmTxt;
    private javax.swing.JButton updTxt;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton uplogoutBtn;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables

    private boolean checkValueInDatabase(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
